name: Deploy API

on:
  push:
    branches: ["main"]
    paths: ["api/**"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      working-directory: ./api
      run: npm ci
      
    - name: Run tests
      working-directory: ./api
      run: npm test || true  # Allow tests to fail for now
      
    # Add your deployment steps here (e.g., Railway, Render, etc.)
    - name: Deploy to Production
      run: echo "Add your deployment commands here"
